### PR TITLE
fix: docker image build

### PR DESCRIPTION
**Pull request by rbarabas**
Fixes docker image build issue

The image fails to build due to a go oauth2 package dependency issue outlined in https://github.com/aws-observability/aws-otel-collector/issues/926. 

During build you would encounter the following error:
```
2023-02-14T20:29:04Z #16 [build 6/7] COPY . /go/src/github.com/netlify/gotrue
2023-02-14T20:29:04Z #16 DONE 0.1s
2023-02-14T20:29:04Z
2023-02-14T20:29:04Z #17 [build 7/7] RUN make build
2023-02-14T20:29:04Z #17 0.419 go build -ldflags "-X github.com/netlify/gotrue/cmd.Version=`git rev-parse HEAD`"
2023-02-14T20:29:06Z #17 1.776 /go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220524215830-622c5d57e401/google/default.go:17:2: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
2023-02-14T20:29:06Z #17 1.776 cloud.google.com/go/compute v1.6.1 (/go/pkg/mod/cloud.google.com/go/compute@v1.6.1/metadata)
2023-02-14T20:29:06Z #17 1.776 cloud.google.com/go/compute/metadata v0.2.0 (/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.0)
2023-02-14T20:29:06Z #17 1.778 make: *** [Makefile:13: build] Error 1
2023-02-14T20:29:06Z #17 ERROR: executor failed running [/bin/sh -c make build]: exit code: 2
2023-02-14T20:29:06Z
2023-02-14T20:29:06Z #10 [build 1/7] FROM docker.io/library/golang:1.15-alpine@sha256:b58c367d52e46cdedc25ec9cd74cadb14ad65e8db75b25e5ec117cdb227aa264
2023-02-14T20:29:06Z ------
2023-02-14T20:29:06Z > [build 7/7] RUN make build:
2023-02-14T20:29:06Z #17 0.419 go build -ldflags "-X github.com/netlify/gotrue/cmd.Version=`git rev-parse HEAD`"
2023-02-14T20:29:06Z #17 1.776 /go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220524215830-622c5d57e401/google/default.go:17:2: ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules:
2023-02-14T20:29:06Z #17 1.776 cloud.google.com/go/compute v1.6.1 (/go/pkg/mod/cloud.google.com/go/compute@v1.6.1/metadata)
2023-02-14T20:29:06Z #17 1.776 cloud.google.com/go/compute/metadata v0.2.0 (/go/pkg/mod/cloud.google.com/go/compute/metadata@v0.2.0)
2023-02-14T20:29:06Z #17 1.778 make: *** [Makefile:13: build] Error 1
2023-02-14T20:29:06Z ------
2023-02-14T20:29:06Z ERROR: failed to solve: executor failed running [/bin/sh -c make build]: exit code: 2
2023-02-14T20:29:06Z Build failed using Buildkit (1)
```

In order to solve this I initially tried to update the problematic dependencies:
```
$ go get cloud.google.com/go/compute/metadata && go mod tidy
```

However, the main issue was the use of golang version 1.15. 

Using golang 1.19 the build concludes successfully:

```
❯ docker build .
failed to fetch metadata: signal: killed

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  8.263MB
Step 1/18 : FROM golang:1.19-alpine as build
1.19-alpine: Pulling from library/golang
af6eaf76a39c: Pull complete
55522c791124: Pull complete
d8a025c151a2: Pull complete
e172ed32e80e: Pull complete
Digest: sha256:6446642017d095caa98505ecdf1df501dd31cb73491229a0fd7080c0e5aea9d5
Status: Downloaded newer image for golang:1.19-alpine
 ---> 42d2560cd624
Step 2/18 : ENV GO111MODULE=on
 ---> Running in 9e3370d736fb
Removing intermediate container 9e3370d736fb
 ---> 79ad5b8407dd
Step 3/18 : ENV CGO_ENABLED=0
 ---> Running in e888920f74ab
Removing intermediate container e888920f74ab
 ---> 41ca17c05263
Step 4/18 : ENV GOOS=linux
 ---> Running in 764786cb6de4
Removing intermediate container 764786cb6de4
 ---> 2378072868a1
Step 5/18 : RUN apk add --no-cache make git
 ---> Running in 0743d961f434
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
(1/7) Installing brotli-libs (1.0.9-r9)
(2/7) Installing nghttp2-libs (1.51.0-r0)
(3/7) Installing libcurl (7.87.0-r1)
(4/7) Installing libexpat (2.5.0-r0)
(5/7) Installing pcre2 (10.42-r0)
(6/7) Installing git (2.38.4-r0)
(7/7) Installing make (4.3-r1)
Executing busybox-1.35.0-r29.trigger
OK: 17 MiB in 23 packages
Removing intermediate container 0743d961f434
 ---> 67dbc93920b5
Step 6/18 : WORKDIR /go/src/github.com/netlify/gotrue
 ---> Running in 2b193e458ac1
Removing intermediate container 2b193e458ac1
 ---> 7a53b0e25abb
Step 7/18 : COPY ./Makefile ./go.* ./
 ---> 0c005865c59f
Step 8/18 : RUN make deps
 ---> Running in 652e6f35dcd0
go: downloading golang.org/x/lint v0.0.0-20210508222113-6edffad5e616
go: downloading golang.org/x/tools v0.1.12
Removing intermediate container 652e6f35dcd0
 ---> 3ba4b093e2c1
Step 9/18 : COPY . /go/src/github.com/netlify/gotrue
 ---> 0e17cde77108
Step 10/18 : RUN make build
 ---> Running in 51931eedfdf0
go build -ldflags "-X github.com/netlify/gotrue/cmd.Version=`git rev-parse HEAD`"
Removing intermediate container 51931eedfdf0
 ---> 3bea51f78ec1
Step 11/18 : FROM alpine:3.7
3.7: Pulling from library/alpine
40223db5366f: Pull complete
Digest: sha256:8421d9a84432575381bfabd248f1eb56f3aa21d9d7cd2511583c68c9b7511d10
Status: Downloaded newer image for alpine:3.7
 ---> bd812700d284
Step 12/18 : RUN adduser -D -u 1000 netlify
 ---> Running in 5463ebb36af2
Removing intermediate container 5463ebb36af2
 ---> e6b0777ba83d
Step 13/18 : RUN apk add --no-cache ca-certificates
 ---> Running in 70d008be5ca1
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/aarch64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20190108-r0)
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 5 MiB in 14 packages
Removing intermediate container 70d008be5ca1
 ---> 9bbdd79389fa
Step 14/18 : COPY --from=build /go/src/github.com/netlify/gotrue/gotrue /usr/local/bin/gotrue
 ---> 3f29c21b3c34
Step 15/18 : COPY --from=build /go/src/github.com/netlify/gotrue/migrations /usr/local/etc/gotrue/migrations/
COPY failed: stat go/src/github.com/netlify/gotrue/migrations: file does not exist
```

Updates the go module files to fix a dependency problem

### CODE REVIEW

**Comment by rbarabas** [comment]
There appears to be another problem related to the build with the Tigris go client and possibly the go version being used:
```
# github.com/tigrisdata/tigris-client-go/api/server/v1
/go/pkg/mod/github.com/tigrisdata/tigris-client-go@v1.0.0-beta.20/api/server/v1/error.go:212:28: undefined: any
/go/pkg/mod/github.com/tigrisdata/tigris-client-go@v1.0.0-beta.20/api/server/v1/marshaler.go:41:19: undefined: io.ReadAll
note: module requires Go 1.18
make: *** [Makefile:13: build] Error 2
```

**Review by terbepetra — APPROVED** [review]

**Comment by rbarabas** [comment]
I believe that the main culprit here was the outdated golang image used so that alone should be sufficient for this build to conclude, without the upgrade of the other components, if that's undesired.

**Comment by rbarabas** [comment]
Confirmed that using the updated image alone is enough for the build to succeed.

**Comment by rbarabas** [comment]
I'm going to leave the updated dependencies in place as everything seems to be in order with them.

**Comment by himank** [comment]
great!

**Pull request merged**
